AVIV-IT/AVIV-IT/Controllers/OnlineShoppingController.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AVI_IT.Models;
using AVI_IT.Utilities;
using AVI_IT.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using static AVI_IT.ViewModels.PriceRangeViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System;

namespace AVI_IT.Controllers
{
  //  [Authorize]
    public class OnlineShoppingController : Controller
    {
        private readonly AvivDataContext _db;
        private UserManager<IdentityUserHelper> userManager;
        public readonly IConfigurationRoot configuration;
        public AddressModel address = new AddressModel();
        public OnlineShoppingController(AvivDataContext db, IWebHostEnvironment env, UserManager<IdentityUserHelper> userManager)
        {
            _db = db;
            this.userManager = userManager;
            configuration = new ConfigurationBuilder()
                       .AddEnvironmentVariables()
                       .AddJsonFile(env.ContentRootPath + "/config.json")
                       .Build();
        }
        public IActionResult Index()
        {
            try
            {
                List<Product> lProd = getList();
                return View(lProd);
            }
            catch (Exception ex)
            {
                global.gLogger.log.Debug("Debug message: ", ex.Message);
                global.gLogger.log.Error(new Exception(), ex.Message);
                global.gLogger.log.Error(new Exception(), ex.StackTrace);
                global.gLogger.log.Fatal("Fatal message: ", ex.Message);

            }
            return NotFound();
        }

        //Get product details
        public IActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                List<Product> lp = getList();
                foreach (var item in lp)
                {
                    if (item.productID == id)
                    {
                        return View(item);
                    }
                }
                
            }
            catch (Exception ex)
            {
                global.gLogger.log.Debug("Debug message: ", ex.Message);
                global.gLogger.log.Error(new Exception(), ex.Message);
                global.gLogger.log.Error(new Exception(), ex.StackTrace);
                global.gLogger.log.Fatal("Fatal message: ", ex.Message);

            }
            return NotFound();
        }

        //Post product details
        [HttpPost]
        [ActionName("Details")]
        public IActionResult ProductDetails(int? id)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    List<Product> products = new List<Product>();
                    if (id == null)
                    {
                        return NotFound();
                    }
                    addProduct(id);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                global.gLogger.log.Debug("Debug message: ", ex.Message);
                global.gLogger.log.Error(new Exception(), ex.Message);
                global.gLogger.log.Error(new Exception(), ex.StackTrace);
                global.gLogger.log.Fatal("Fatal message: ", ex.Message);

            }
            return RedirectToAction(nameof(Index));

        }
        [HttpGet]
        [ActionName("Remove")]
        public IActionResult RemoveFromCart(int? id)
        {
            try
            {
                List<Product> products = HttpContext.Session.Get<List<Product>>("products");
                if (products != null)
                {
                    var product = products.FirstOrDefault(m => m.productID == id);
                    if (product != null)
                    {
                        products.Remove(product);
                        HttpContext.Session.Set("products", products);

                    }
                    return View("Cart", products);
                }
                else
                {
                    return View("EmptyCart");
                }
            }
            catch (Exception ex)
            {
                global.gLogger.log.Debug("Debug message: ", ex.Message);
                global.gLogger.log.Error(new Exception(), ex.Message);
                global.gLogger.log.Error(new Exception(), ex.StackTrace);
                global.gLogger.log.Fatal("Fatal message: ", ex.Message);

            }
            return NotFound();

        }
        public IActionResult Cart(int? id)
        { 
            try
            {
                List<Product> products = HttpContext.Session.Get<List<Product>>("products");
                if (products != null)
                {
                    if (products.Count() > 0)
                    {
                        HttpContext.Session.Set("products", products);

                        return View(products);
                    }
                    else
                        return View("EmptyCart");

                }
                else
                {
                    return View("EmptyCart");
                }
            }
            catch (Exception ex)
            {
                global.gLogger.log.Debug("Debug message: ", ex.Message);
                global.gLogger.log.Error(new Exception(), ex.Message);
                global.gLogger.log.Error(new Exception(), ex.StackTrace);
                global.gLogger.log.Fatal("Fatal message: ", ex.Message);

            }
            return NotFound();
        }
        public IActionResult EmptyCart()
        {
            return View();
        }
        
        [HttpGet]
        [ActionName("Add")]
        public IActionResult AddToCart(int? id)
        {
          try
            {
                List<Product> products = addProduct(id);
                return View("Cart", products);
            }
            catch (Exception ex)
            {
                global.gLogger.log.Debug("Debug message: ", ex.Message);
                global.gLogger.log.Error(new Exception(), ex.Message);
                global.gLogger.log.Error(new Exception(), ex.StackTrace);
                global.gLogger.log.Fatal("Fatal message: ", ex.Message);

            }
            return NotFound();
            
        }
        [HttpPost]
        public IActionResult Add(int? id)
        {
            try
            {
                List<Product> products = addProduct(id);
                return View("Cart", products);
            }
            catch (Exception ex)
            {
                global.gLogger.log.Debug("Debug message: ", ex.Message);
                global.gLogger.log.Error(new Exception(), ex.Message);
                global.gLogger.log.Error(new Exception(), ex.StackTrace);
                global.gLogger.log.Fatal("Fatal message: ", ex.Message);

            }
            return NotFound();
            
        }
        [HttpGet]
        [ActionName("RemoveOne")]
        public IActionResult RemoveOneFromCart(int? id)
        {
            try
            {
                List<Product> products = removeProduct(id);
                Product prod = new Product();
                prod = products.FirstOrDefault(m => m.productID == id);
                if (prod != null)
                {
                    if (prod.prodCount == 0)
                    {
                        products.Remove(prod);
                        HttpContext.Session.Set("products", products);
                        return View("Cart", products);
                    }
                }

                return View("Cart", products);
            }
            catch (Exception ex)
            {
                global.gLogger.log.Debug("Debug message: ", ex.Message);
                global.gLogger.log.Error(new Exception(), ex.Message);
                global.gLogger.log.Error(new Exception(), ex.StackTrace);
                global.gLogger.log.Fatal("Fatal message: ", ex.Message);

            }
            return NotFound();
            
        }
        //[HttpPost]
        //public IActionResult RemoveOne(int? id)
        //{
        //    //List<Product> products = removeProduct(id);
        //    //return View("Cart", products);
        //    List<Product> products = removeProduct(id);
        //    Product prod = new Product();
        //    prod = products.FirstOrDefault(m => m.productID == id);
        //    if (prod != null)
        //    {
        //        if (prod.prodCount == 0)
        //        {
        //            products.Remove(prod);
        //            return View("Cart", products);
        //        }
        //    }

        //    return View("Cart", products);
        //}
        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            try
            {
                List<Product> products = HttpContext.Session.Get<List<Product>>("products");
                CartModel cartUser = new CartModel();
                var userId = HttpContext.Session.GetString("userID");
                cartUser.userID = userId;
                _db.cart.Add(cartUser);
                _db.SaveChanges();
                HttpContext.Session.Set("cartUser", cartUser);

                foreach (var item in products)
                {
                    ProductCart cart = new ProductCart();
                    cart.cartID = cartUser.cartID;
                    cart.productID = item.productID;
                    cart.quantity = item.prodCount;
                    cart.totalCost = item.price * item.prodCount;

AVIV-IT/AVIV-IT/Views/OnlineShopping/Cart.cshtml
@model List<AVI_IT.Models.Product>


    <div class="container">
        <fieldset>
            <h3 class="heading3" style="margin-bottom:30px">Cart</h3>

            <div class="row">

                <table class="table">
                    <thead class="table-dark table-borderless">
                        <tr>
                            <th></th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Product type</th>
                            <th scope="col">Quantity</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td scope="row">
                                    <img src="~/@item.image" class="img-fluid" style="max-width:150px;height:150px;" />
                                </td>
                                <td>@item.productName</td>
                                <td>@item.price</td>
                                <td>@item.productType.type</td>
                                <td>@item.prodCount</td>
                                <td>
                                    <div class="row">
                                        <div class="col-2">
                                            <form method="post">
                                                <a asp-action="Add" asp-controller="OnlineShopping" asp-route-id="@item.productID" class="btn btn-warning">
                                                    <i class="fas fa-plus-circle"></i>
                                                </a>
                                            </form>
                                        </div>
                                        <div class="col-2">
                                            <form method="post">
                                                <a asp-action="RemoveOne" asp-controller="OnlineShopping" asp-route-id="@item.productID" class="btn btn-warning">
                                                    <i class="fas fa-minus-circle"></i>
                                                </a>
                                            </form>
                                        </div>
                                        <div class="col-2">
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>

                                            <!-- Modal -->
                                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">Remove Product</h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            Are you sure to delete this product from cart?
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                            <a asp-action="Remove" asp-controller="OnlineShopping" asp-route-id="@item.productID" class="btn btn-danger ">
                                                                <i class="fas fa-trash-alt"></i></a>
                                                           
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                          </div>
                                    </div>


                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="row py-5">
                <div class="col-6">
                    
                </div>
                @if (@Model.Count() > 0)
                {
                    <div class="col-6 text-right">
                        <h5><strong>Total Amount: $</strong>@Model.Sum(m => m.price * m.prodCount)AUD</h5>
                        <a asp-action="Checkout" asp-controller="OnlineShopping" class="btn btn-info">Go to checkout</a>
                    </div>
                }

            </div>
        </fieldset>

    </div>

AVIV-IT/AVIV-IT/Views/OnlineShopping/EmptyCart.cshtml
<div class="container" style="margin: 0 0 500px 100px">
    <br />
    <h3>Your cart is empty</h3>
    <br />
    <br />
    <div class="col">
        <a asp-controller="OnlineShopping" asp-action="Index">
            <input type="button" class="btn btn-success btn-sm" value="Go back" />
        </a>
    </div>
</div>

AVIV-IT/AVIV-IT/Views/OnlineShopping/Index - Copy.cshtml
@*@model AVI_IT.ViewModels.ProductViewModel


<div class="container" style="margin: 20px 0 20px 0">
    <div class="row">
        <div class="col-4 border-right">

            <div class="accordion" id="accordionPanelsStayOpenExample">

                <div class="accordion-item">
                    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                            Category
                        </button>
                    </h2>
                    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                        <div class="accordion-body">
                            @foreach (var item in Model.proType)
                            {
                                @Html.CheckBoxFor(k => item.bType) @item.type<br />

                            }
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                            PriceRange
                        </button>
                    </h2>
                    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
                        <div class="accordion-body">
                            @foreach (var item in Model.proRange)
                            {
                                @Html.CheckBoxFor(k => item.bRange) @item.range<br />

                            }
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="col-8">

            <div class="row row-cols-1 row-cols-md-3 g-4">
                display each item to the customer
                Expected Outcome-for UI testing Purpose
                <div class="col">
                    <a asp-controller="OnlineShopping"
                       asp-action="ItemDetail">
                        <div class="card border-dark h-100" id="cardShopping">
                            <img src="~/images/product1.jpg" class="card-img-top" />
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(m => m.productName)</h5>
                                <p class="card-text text-muted">@Html.DisplayFor(m => m.type) </p>
                                <p class="card-text">@Html.DisplayFor(m => m.productDes) </p>
                                <div class="row">
                                    <div class="col-4">
                                        <strong>$@Html.DisplayFor(m => m.price)</strong>
                                    </div>
                                    <div class="col-8">
                                        <input class="btn btn-success" type="button" value="Add To Cart" />

                                     </div>
                                </div>
                            </div>

                        </div>
                    </a>
                </div>

                <div class="col">
                    <a asp-controller="OnlineShopping"
                       asp-action="ItemDetail">
                        <div class="card border-dark h-100" id="cardShopping">
                            <img src="~/images/product1.jpg" class="card-img-top" />
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(m => m.productName)</h5>
                                <p class="card-text text-muted">@Html.DisplayFor(m => m.type) </p>
                                <p class="card-text">@Html.DisplayFor(m => m.productDes) </p>
                                <div class="row">
                                    <div class="col-4">
                                        <strong>$@Html.DisplayFor(m => m.price)</strong>
                                    </div>
                                    <div class="col-8">
                                        <input class="btn btn-success" type="button" value="Add To Cart" />

                                    </div>
                                </div>
                            </div>

                        </div>
                    </a>
                </div>


                <div class="col">
                    <a asp-controller="OnlineShopping"
                       asp-action="ItemDetail">
                        <div class="card border-dark h-100" id="cardShopping">
                            <img src="~/images/product1.jpg" class="card-img-top" />
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(m => m.productName)</h5>
                                <p class="card-text text-muted">@Html.DisplayFor(m => m.type) </p>
                                <p class="card-text">@Html.DisplayFor(m => m.productDes) </p>
                                <div class="row">
                                    <div class="col-4">
                                        <strong>$@Html.DisplayFor(m => m.price)</strong>
                                    </div>
                                    <div class="col-8">
                                        <input class="btn btn-success" type="button" value="Add To Cart" />

                                    </div>
                                </div>
                            </div>

                        </div>
                    </a>
                </div>


                <div class="col">
                    <a asp-controller="OnlineShopping"
                       asp-action="ItemDetail">
                        <div class="card border-dark h-100" id="cardShopping">
                            <img src="~/images/product1.jpg" class="card-img-top" />
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(m => m.productName)</h5>
                                <p class="card-text text-muted">@Html.DisplayFor(m => m.type) </p>
                                <p class="card-text">@Html.DisplayFor(m => m.productDes) </p>
                                <div class="row">
                                    <div class="col-4">
                                        <strong>$@Html.DisplayFor(m => m.price)</strong>
                                    </div>
                                    <div class="col-8">
                                        <input class="btn btn-success" type="button" value="Add To Cart" />

                                    </div>
                                </div>
                            </div>

                        </div>
                    </a>
                </div>

                <div class="col">
                    <a asp-controller="OnlineShopping"
                       asp-action="ItemDetail">
                        <div class="card border-dark h-100" id="cardShopping">
                            <img src="~/images/product1.jpg" class="card-img-top" />
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(m => m.productName)</h5>
                                <p class="card-text text-muted">@Html.DisplayFor(m => m.type) </p>
                                <p class="card-text">@Html.DisplayFor(m => m.productDes) </p>
                                <div class="row">
                                    <div class="col-4">
                                        <strong>$@Html.DisplayFor(m => m.price)</strong>
                                    </div>
                                    <div class="col-8">
                                        <input class="btn btn-success" type="button" value="Add To Cart" />

                                    </div>
                                </div>
                            </div>

                        </div>
                    </a>
                </div>

            </div>

        </div>

    </div>
</div>*@

AVIV-IT/AVIV-IT/Views/OnlineShopping/Index.cshtml
@using AVI_IT.Models
@model List<Product>
@{
    ViewData["Title"] = "Index";
}
<div class="container-fluid" >
   <div class="row">
       <p class="heading3" style="font-size:30px">AVIV-IT Products</p>
   </div>
    <div class="row">
        <div class="col-10">
            <div class=" row">
                @foreach (var product in Model)
                {
                    <div class="col-4">
                        <div class="card mb-4 ">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-bold">
                                    <label style="font-size: 23px;color: steelblue;text-align:center">@product.productName</label>
                                </h4>
                                <img src="~/@product.image" alt="Card Image" class="card-img-top" style="max-width:250px;height:250px;" />

                            </div>
                            <div class="card-body">
                                <div class="d-flex justify-cotent-between">
                                    <div class="btn-group">
                                        <label style="font-size: 20px; color: darkred;margin:0 15px 0 0 "><b>Price: $@product.price</b></label>
                                    </div>
                                    <a asp-action="Details" asp-controller="OnlineShopping" asp-route-id="@product.productID" class="btn btn-success">More Detail</a>
                                </div>
                            </div>
                        </div>

                    </div>
                }

            </div>
        </div>

        <div class="col-2 py-2">
          @await Component.InvokeAsync("OnlineShopping") 
        </div>

    </div>
</div>

AVIV-IT/AVIV-IT/Views/OnlineShopping/Index2.cshtml
@model AVI_IT.ViewModels.TestViewModel
@*@using AVI_IT.ViewModels
@using AVI_IT.Models
@model Tuple<List<ProductViewModel>, List<ProductType>, PriceRange[]>*@

<fieldset>
    @using (Html.BeginForm())
    {
        <div class="container" style="margin: 20px 0 20px 0">
            <div class="row">
                <div class="col-4 border-right">

                    <div class="accordion" id="accordionPanelsStayOpenExample">

                        <div class="accordion-item">
                            <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                                    Category
                                </button>
                            </h2>
                            <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                                <div class="accordion-body">
                                    @*@foreach (var item in Model)
                                        {
                                                
                                                @Html.CheckBoxFor(k => item.productType.bType) @item.productType.type < br />
                                            

                                        }*@
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                                    PriceRange
                                </button>
                            </h2>
                            <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
                                <div class="accordion-body">
                                    @*@foreach (var item in Model)
                                    {

                                            @Html.CheckBoxFor(k => item.proRange.bRange) @item.proRange.range<br />
                                        


                                    }*@
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-8">

                    <div class="row row-cols-1 row-cols-md-3 g-4">
                        @*display each item to the customer*@
                        @* Expected Outcome-for UI testing Purpose*@

                        @foreach (var item in Model.lProd)
                        {
                            <div class="col">
                                <a asp-controller="OnlineShopping"
                                   asp-action="ItemDetail"
                                   asp-route-id="@item.productID">
                                    <div class="card border-dark h-100" id="cardShopping">
                                        <img src="~/images/product1.jpg" class="card-img-top" />
                                        <div class="card-body">
                                            <h5 class="card-title">@Html.DisplayFor(m => item.productName)</h5>
                                            <p class="card-text text-muted">@Html.DisplayFor(m => item.productType.type) </p>
                                            <p class="card-text">@Html.DisplayFor(m => item.productDes) </p>
                                            <div class="row">
                                                <div class="col-4">
                                                    <strong>$@Html.DisplayFor(m => item.price)</strong>
                                                </div>
                                                <div class="col-8">
                                                    <input class="btn btn-success" type="button" value="Add To Cart" />

                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </a>
                            </div>

                        }

                    </div>
                </div>
            </div>
        </div>
    }
    </fieldset>