AVIV-IT/AVIV-IT/ViewModels/CreateRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AVI_IT.ViewModels
{
    public class CreateRoleViewModel
    {
        [Required]
        [Display(Name = "Role Name")]
        public string RoleName {get;set;}
    }
}

AVIV-IT/AVIV-IT/ViewModels/ManageRoleViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AVI_IT.ViewModels
{
    public class ManageRoleViewModel
    {
        public string userID { get; set; }

        public string roleID { get; set; }
        public List<SelectListItem> userList { get; set; }

        public List<SelectListItem> roleList { get; set; }
    }
}

AVIV-IT/AVIV-IT/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AVI_IT.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AVI_IT.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUserHelper> userManager;
        List<string> userList;

        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUserHelper> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            var users1 = userManager.Users;
            userList = new List<string>();
            foreach (var user in users1) userList.Add(user.Email);
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    IdentityRole identityRole = new IdentityRole
                    {
                        Name = model.RoleName
                    };
                    IdentityResult result = await roleManager.CreateAsync(identityRole);
                    if (result.Succeeded) return View("Display", roleManager.Roles);

                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
                return View("Display", roleManager.Roles);
            }
            catch(Exception ex)
            {
                global.gLogger.log.Debug("Debug message: ", ex.Message);
                global.gLogger.log.Error(new Exception(), ex.Message);
                global.gLogger.log.Error(new Exception(), ex.StackTrace);
                global.gLogger.log.Fatal("Fatal message: ", ex.Message);
                return View("Display", roleManager.Roles);
            }
        }

        //[HttpGet]
        //public IActionResult ManageRole()
        //{
        //    ManageRoleViewModel mrole = new ManageRoleViewModel();
        //    FillArray(mrole);
        //    return View(mrole);
        //}
        //[HttpPost]
        //public async Task<IActionResult> ManageRole(ManageRoleViewModel mrole)
        //{
        //    var role = await roleManager.FindByIdAsync(mrole.roleID);
        //    var user = await userManager.FindByIdAsync(mrole.userID);
        //    if(null == role) return View("Not Found");
        //    if(!(await userManager.IsInRoleAsync(user, role.Name)))
        //    {
        //        var result = await userManager.AddToRoleAsync(user, role.Name);
        //    }

        //    return View("Display", roleManager.Roles);
        //}

        //private void FillArray(ManageRoleViewModel mrole)
        //{
        //    var users = userManager.Users;
        //    mrole.userList = new List<SelectListItem>();
        //    foreach (var user in users)
        //    {
        //        SelectListItem item = new SelectListItem();
        //        item.Text = user.UserName;
        //        item.Value = user.Id;
        //        mrole.userList.Add(item);
        //    }

        //    var roles = roleManager.Roles;
        //    mrole.roleList = new List<SelectListItem>();
        //    foreach (var role in roles)
        //    {
        //        SelectListItem item = new SelectListItem();
        //        item.Text = role.Name;
        //        item.Value = role.Id;
        //        mrole.roleList.Add(item);
        //    }

        //}
    }
}

AVIV-IT/AVIV-IT/Views/Administration/CreateRole.cshtml
@model AVI_IT.ViewModels.CreateRoleViewModel

@{ ViewBag.Title = "Create a new role"; }
<div class="container-sm">

    <h3 class="heading3"> Create role</h3>
    <div class="row">
        <div class="col-9">
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="RoleName"></label>
                    <input asp-for="RoleName" class="form-control" />
                    <span asp-validation-for="RoleName" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Create Role</button>
                <input type="button" class=" btn btn-primary" value="Back" onclick="location.href='@Url.Action("Index", "AdminPage")'" />
</form>
        </div>
    </div>
</div>

AVIV-IT/AVIV-IT/Views/Administration/Display.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>

<div class="container-sm">

    <b class="heading3">Roles</b>
    <table class=" table table-striped table-dark">

        <tr>
            <th>@Html.DisplayNameFor(m => m.Id)</th>
            <th>@Html.DisplayNameFor(m => m.Name)</th>

        </tr>
        @foreach (var v in Model)
        {
            <tr>
                <td>@v.Id</td>
                <td>@v.Name</td>
            </tr>
        }
    </table>
    <div class="col">
        <input type="button" class=" btn btn-primary form-control" value="Back" onclick="location.href='@Url.Action("CreateRole", "Administration")'" />
    </div>
</div>

AVIV-IT/AVIV-IT/Views/Administration/ManageRole.cshtml
@model AVI_IT.ViewModels.ManageRoleViewModel

<div class="container-sm">
    <fieldset>
        @using (Html.BeginForm())
        {
            <table>
                <tr><td>@Html.LabelFor(m => m.userList)</td><td>@Html.DropDownListFor(m => m.userID, new SelectList(Model.userList, "Value", "Text"), "Select User", new { @class = "form-control" })</td></tr>
                <tr><td>@Html.LabelFor(m => m.roleList)</td><td>@Html.DropDownListFor(m => m.roleID, new SelectList(Model.roleList, "Value", "Text"), "Select Role", new { @class = "form-control" })</td></tr>

                <tr><td></td><td><button type="submit">Add Role to the user</button></td></tr>

            </table>
          }
    </fieldset>

</div>